on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-init
        with:
          args: 'init "-l config"'
      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'
      - name: West Build (wirelice)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-wirelice
        with:
          args: 'build "-s zmk/app -b wirelice -- -DZMK_CONFIG=/github/workspace/config"'
      - name: Archive (wirelice)
        uses: actions/upload-artifact@v2
        with:
          name: wirelice
          path: build/zephyr/zmk.uf2
      - name: West Build (m0110a)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-m0110a
        with:
          args: 'build "-s zmk/app -b m0110a -- -DZMK_CONFIG=/github/workspace/config"'
      - name: Archive (m0110a)
        uses: actions/upload-artifact@v2
        with:
          name: m0110a
          path: build/zephyr/zmk.uf2